title: Knowledge MD Extractor
description: Turn readable web pages into editable Markdown locally in Chrome.
url: https://haraheri.github.io
baseurl: /knowledge-md-extractor-privacy
markdown: kramdown

exclude:
  - README.md
